### ISSUE TITLE
Accept only Images

### ISSUE THREAD

**Issue by warrenferns** [githubcrce/img2pdf#4]
**Describe the solution you'd like**
`Choose Files` must be able to select only files of image formats such as `png` / `jpg` / `jpeg`

**Comment by bauripalash** [comment]
How about `String.prototype.endsWith()`
We could use a iterating loop.  Or maybe  a plain old switch case.

Another possible solution is to use regular expressions. 

But on few *nix systems file extension can be nonexistent.  So current mime type filtering logic works best.
